//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhThuBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANH
    {
        public BANH()
        {
            this.CTDHs = new HashSet<CTDH>();
            this.KHUYENMAIs = new HashSet<KHUYENMAI>();
            this.YKIENs = new HashSet<YKIEN>();
        }
    
        public int MaBanh { get; set; }
        public string TenBanh { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public string MoTa { get; set; }
        public string HinhMinhHoa { get; set; }
        public Nullable<int> MaCD { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public Nullable<int> SoLuongBan { get; set; }
    
        public virtual CHUDE CHUDE { get; set; }
        public virtual LOAIBANH LOAIBANH { get; set; }
        public virtual ICollection<CTDH> CTDHs { get; set; }
        public virtual ICollection<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual ICollection<YKIEN> YKIENs { get; set; }
    }
}
