//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhThuBakery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CSDLBanhKemEntities5 : DbContext
    {
        public CSDLBanhKemEntities5()
            : base("name=CSDLBanhKemEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BANH> BANHs { get; set; }
        public DbSet<CHUDE> CHUDEs { get; set; }
        public DbSet<CTDH> CTDHs { get; set; }
        public DbSet<DONDH> DONDHs { get; set; }
        public DbSet<HTTT> HTTTs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public DbSet<LIENHE> LIENHEs { get; set; }
        public DbSet<LOAIBANH> LOAIBANHs { get; set; }
        public DbSet<NHOMQUANTRI> NHOMQUANTRIs { get; set; }
        public DbSet<QUANGCAO> QUANGCAOs { get; set; }
        public DbSet<QUANTRI> QUANTRIs { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TINTUC> TINTUCs { get; set; }
        public DbSet<YKIEN> YKIENs { get; set; }
    }
}
