//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhThuBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public int MaKM { get; set; }
        public Nullable<int> MaBanh { get; set; }
        public Nullable<int> GiaGiam { get; set; }
    
        public virtual BANH BANH { get; set; }
    }
}
