//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhThuBakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YKIEN
    {
        public int MaYKien { get; set; }
        public int MaBanh { get; set; }
        public string HoTen { get; set; }
        public Nullable<System.DateTime> NgayYKien { get; set; }
        public string NoiDung { get; set; }
        public Nullable<bool> Duyet { get; set; }
    
        public virtual BANH BANH { get; set; }
    }
}
